### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by vijayakumarksv** [emrade/flutter-social#1]
When i click the login button its nothing work?

**Comment by emrade** [comment]
@vijayakumarksv When you click on login. It should navigate to the list of feeds.
That didn't happen?

**Comment by vijayakumarksv** [comment]
When i click the login or Sign in is not working

**Comment by emrade** [comment]
@vijayakumarksv please be specific, does it throw an error when you click on it? Or the button does nothing?

**Comment by vijayakumarksv** [comment]
i need to click that button its goes to the next page. is it does any screen?

**Comment by emrade** [comment]
@vijayakumarksv When you click the login button it then navigates to the home page.
Mind you, I did not implement any login logic. The app is a depiction of what a social media app might look like. 

Does that answer your question?

**Comment by bdk-koento** [comment]
Absolutely, in landing page sign up and login button does not navigate anywhere

**Comment by vijayakumarksv** [comment]
Yes , but i need to navigate somewhere how to do ?

**Comment by bdk-koento** [comment]
> Yes , but i need to navigate somewhere how to do ?

I'm trying to find out actually but could not make it so far. When i found the solution, i'll let you know:)

**Comment by vijayakumarksv** [comment]
thanks

**Comment by emrade** [comment]
> 
> 
> > Yes , but i need to navigate somewhere how to do ?
> 
> I'm trying to find out actually but could not make it so far. When i found the solution, i'll let you know:)

@bdk-koento Thanks for your comment. I have tried to possibly replicate this issue you guys have but i can't seem to. If you could give me more information i would be glad.
